### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [horganke/project7#1]
When I submit a blank form, I'm getting an `Internal Server Error`. Can you fix this?

**Comment by horganke** [comment]
All fixed!

**Comment by chrisvfritz** [comment]
:+1: :tada: Excellent! I really like the versatility in the kind of data people can search for.

## Points of improvement for future projects

### Ruby indentation

The standard indentation for Ruby (`.rb`) files is actually with two-space soft-tabs rather than hard-tabs. See if you can update your text editor to use two-space soft-tabs for all Ruby files. If you have trouble figuring it out, [this page may be helpful](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md). If it's not, just let me know and I'll be happy to point you in the right direction.
